---
title: "Likert scales - horizontal bar"
output: html_notebook
---

## Likert scale counts based on Reuters 2018 Digital Report Tables

Libraries
```{r libraries}
library(tidyverse)
```


```{r data}
#Thinking about online news, I am concerned about what is real and what is fake on the internet.

real_fake <- read_csv("data/misinfo/concern-real-vs-fake-seg.csv")

# don't use column name as key or value in `gather()`!!!

stack_real_fake <- real_fake %>% select(segment, `Not at all concerned`, `Not very concerned`, `Somewhat concerned`, `Very concerned`, `Extremely concerned`) %>% gather(concern, percent, `Not at all concerned`, `Not very concerned`, `Somewhat concerned`, `Very concerned`, `Extremely concerned`)

stack_real_fake <- stack_real_fake %>% mutate(percent_new = percent * 100)

#To what extent, if at all, are you concerned about the following: - Poor journalism (factual mistakes, dumbed down stories, misleading headlines/clickbait)

poor_J <- read_csv("data/misinfo/poor-journalism-agreement-seg.csv")

stack_poor_J <- poor_J %>% select(segment, `Strongly disagree`, `Tend to disagree`, `Neither agree nor disagree`, `Tend to agree`, `Strongly agree`) %>% gather(agreement, percent, `Strongly disagree`, `Tend to disagree`, `Neither agree nor disagree`, `Tend to agree`, `Strongly agree`)

stack_poor_J <- stack_poor_J %>% mutate(percent_new = percent * 100)
```

```{r themes}
fake_theme <- function(){
  list(
      theme_minimal(),
      scale_fill_manual(values=c('#a6611a','#dfc27d','#f5f5f5','#80cdc1','#018571'), 
                       name="Level of Concern",
                       breaks=c("Extremely concerned", "Very concerned", "Somewhat concerned", "Not very concerned", "Not at all concerned"),
                       labels=c("Extremely concerned", "Very concerned", "Somewhat concerned", "Not very concerned", "Not at all concerned")) 
    )
}

poorJ_theme <- function(){
  list(
      theme_minimal(),
      scale_fill_manual(values=c('#a6611a','#dfc27d','#f5f5f5','#80cdc1','#018571'), 
                       name="Level of Agreement",
                       breaks=c("Strongly disagree", "Tend to disagree", "Neither agree nor disagree", "Tend to agree", "Stronly agree"),
                       labels=c("Strongly disagree", "Tend to disagree", "Neither agree nor disagree", "Tend to agree", "Stronly agree")) 
    )
}
```

```{r fake plot}
fake_plot <- ggplot(stack_real_fake, aes(segment, percent_new, width=.5, fill = percent_new)) + #reorder(column, by_what)
  geom_bar(aes(fill = concern), stat = "identity", position = "fill") + 
  fake_theme() +
  coord_flip() +
  labs(title = "I am concerned about what is real and what is fake on the internet:", x = "Segment", y = "Percent", caption = "Source: Reuters 2018 Digital News Report") 
  #geom_text(size = 3, position = position_stack(vjust = 0.5))


fake_plot
```

```{r poorJ plot}
poorJ_plot <- ggplot(stack_poor_J, aes(segment, percent_new, width=.5, fill = percent_new)) + #reorder(column, by_what)
  geom_bar(aes(fill = agreement), stat = "identity", position = "fill") + 
  poorJ_theme() +
  coord_flip() +
  labs(title = "Concerned about Poor journalism (factual mistakes, dumbed down stories, misleading headlines/clickbait):", x = "Segment", y = "Percent", caption = "Source: Reuters 2018 Digital News Report") 
  #geom_text(aes(label = percent_new), colour = "white", hjust = 1.3)

poorJ_plot

```

